export enum Routes {
    Setup = '/konfiguracja',
    Home = '/tablica',
    NewPost = '/tablica/nowypost',
    Login = '/login',
    Registration = '/rejestracja',
    Profile = '/profil',
    AddedGoalsWithoutSubTarget = '/cele/dodane/bezpodcelu',
    EditGoal = '/cele/edycja',
    AddTask = '/cele/nowy',
    AddSubtask = '/cele/nowy/podcel',
    AddSubTaskForm = '/cele/nowy/podcel/formularz',
    SaveTaskAndSubtask = '/cele/zapisz',
    Goals = '/cele',
    TimelineGoals = '/cele/nowy/timeline',
    Chat = '/czat',
    ChatWindow = '/czat/:id',
    Events = '/wydarzenia',
    AddGoalReasults = '/cele/wyniki'
}
